### ISSUE TITLE
Proposal for improved build time and stability 

### ISSUE THREAD

**Issue by alexwolfe** [gravitational/next#806] opened 2022-01-24 16:59 UTC
Please **create a short proposal** (should be completed by Tuesday) on how to fix the recurring build issues we currently have and decrease the build time. 

### Goal
Speed up the current build process and improve the stability of the builds. 

### Tasks
- Identity briefly the key areas that broke the build process. Please provide a list of issues we've had recently and in the past that have caused failures along with if they are still relevant as failure points. 
- Propose methods to increase the build speed along with benefits and drawbacks of the approach 
- Assume the repositories will be separated in the future but for now we’ll have the Website and Docs combined (no blog) 
- include time estimates on how long this will take to complete along with the expected benefits
- Please outline what the current issues are clearly and concisely

**Comment by iAdramelk** [comment] 2022-01-24 17:04
@alexwolfe Hey, Alex. Can you elaborate what problems do you mean exactly? After we merged Katya's fix last week we don't have OoM errors and we don't have serverless functions size errors. So the builds should work now. Is there some other issues which are breaking the builds right now?

**Comment by alexwolfe** [comment] 2022-01-25 16:59
I've updated that tasks above, they should be clear. Let me know if you have any further questions. Thanks.

**Comment by iAdramelk** [comment] 2022-01-25 18:45
@alexwolfe 

So we have have the following errors that broke builds in the last month or so:

**1) Out of Memory errors:**

Large number of entry points to the web pack bundle AND update to the `next@12` which had `outputFileTracing` enabled caused this one.

`outputFileTracing` was consuming twice as much of memory as before combined with merging 200+ posts (which are for now each is considered as an entry point) from the blog caused OoM error.

We disabled `outputFileTracing` option and moved blog pages to the separate broach. It solved this problem for now, but it could return if we have more then 1500+ entry points (entry point !== page).

Possible solutions (will go in the more details later):

- Split repo in 3 parts – will temporarily solve the problem, but with the way blogposts and docs are implemented now, it will still return in the future.
- Migrate all blog posts to Contentful - it will solve both build time and memory issues for the blog. It will also work with any number of posts when.
- Replace 800+ docs entries with one dynamic page entry that will render docs pages on demand. I will need to do some updates to the docs content and plugins, but it will be scalable to any number of doc versions and pages without build speed and memory issues.
- If we don't migrate blog to Contnentful, we can do to it the same optimisations, as to the docs above.

**2) serverless functions size errors:**

This one again was caused by combination of merging blog posts and `outputFileTracing`.

Next builds on Vercel tries to be very smart - if we have dynamically rendered pages, like a list of blog posts, it tries to find all possible files that this dynamic page may need to use and builds it to the serverless function, which it then tries to deploy to AWS. AWS on the other hand have a strict memory limit of 50Mb for each function.

In our case the problem was the following: We were loading images for the first five posts and to do that we wrote image importing function the way that any image in the blog folder could be imported. Vercel read this code and decided to include all files inside the images folder to the function, just to make sure that it does not miss anything.

We solved it for now, but it can return after update to the new version of the Next.

Some ways to solve this problem in more future-proof way:

- Migrating posts to Contentful will solve this problem automatically.
- If we don't migrate to Contentful, we need to remove references to the image's folder from the Next page, and move them to the public folder on build ourselves.

**3) Content errors:**

We have some pretty strict validations on build that will break it of something is forgotten in the original code:

- Blog posts will not build if there are errors in the names or imports of the used components, like subscription forms.
- Docs will not build, if broken components are used.
- If code block uses syntax that is not supported, it will break the build.

These errors are breaking the build intentionally so that authors can see if the did something wrong. All these errors are tested by staging deploys, linters and in the case of docs with a special markdown linter, so if proper PR process is used they will not go to the master. BUT, if somebody uses Github UI to commit changes directly without using branches, it can break the build.

We can make these check less strict and make build work with these problems, only breaking the corresponding pages, but it is trade-off – there is a change that we will not find about these errors for a long time this way.

----

About the build time.

Current full build time is 12-17m.

It consists of:

- Cloning repo with all submodules ~ 3m.
- Restoring cache and installing dependencies ~ 1,5m.
- Build itself ~ 8-10m.
- Updating production version and updating build cache ~ 1,5-2m.


Splitting the docs and all of their submodules will make main site cloning faster. Most of the time now spent on cloning the main `teleport` repo as a submodule. But  the `docs` repo will still have long cloning time.

We can make `installing dependencies` step a little faster by switching from `yarn` to `pnpm`, but not a LOT faster.

Fastest way to make build step faster is to implement this  https://github.com/gravitational/next/issues/744 . It will make builds two times faster (4-5m instead of 8-10m), but will require us to manually retest all css styles and fix possible regressions. `babel` and `swc` use different `styled-components` compilers which works a little different from each other.

Replacing all 800+ mdx pages for docs with one dynamic route will also seriously reduce memory consumption and increase build time, but it is harder to implement.

Replacing `styled-components` with something that does not require runtime and is not bundled as JS can also help both with memory and speed, but is time consuming and effect will be relatively small compared with `swc` and updating docs to use one entry.

---

Full list of thing that can be done:

1. Enable swc:
  - Will reduce build time twice.
  - Will not affect memory.
  - Will require thorough testing of all pages, can be done in relatively small amount of time time (there are not a lot of regressions, main  problem is with finding them all, not fixing).
2. Move docs to the separate repo:
  - Will decrease both site and docs build time.
  - Will reduce memory problem for a time, but it will still return in the future for the docs site.
  - Can be done relatively fast, because logic for site and docs is mostly separate.
3. Port blog to Contentful (IF we port all post there):
  - Will fix build speed and memory problems.
  - Will fix serverless function size problem once and for all.
  - Will prevent build errors on syntax problems in posts.
  - Will allow up to update blog without rebuilding site.
  - Integration can be done relatively fast, but migrating all posts can take a lot of time.
  - P. S. If we move content to Contentful, we can probably skip moving blog to the separate repo – it will be just 2 functions of ~500 LOC that could show blog posts on demand without rebuilding everything.
4. Rewrite docs logic to use one entry for all pages:
  - Will fix docs memory and speed problems once and for all.
  - Will allow us to only build current version at the build time and build other pages on demand.
  - Will prevent build errors on syntax errors in docs.
  - Requires some time on research and rewrites to make sure that everything works with Vercel's serverless functions as expected.
  - Even if Vercel works as expected, we will need to spend couple of weeks on implementing it and updating docs syntax in the main repo.
5. Make build more lenient to some errors in blogposts and docs:
  - Fast to implement, but we may miss some errors this way.
6. Removing `styled-compoents` and `styled-system`:
  - Hard to estimate how it will affect build time and memory usage, but will have a lot of other benefits by simplifying code, reducing number of dependencies, fixing bunch of hard to predict problems and other stuff.
  - Will take a lot of time, so maybe it is better to start from `docs` or `blog` because they are small and depending on results, updating main site with it.

I can either write more in-depth proposal for any of these tasks or start working on them. Please let me know what I should focus on.

**Closed** 2022-02-01 00:44 UTC
Labels: P1
