### ISSUE TITLE
Doc side navigation expanding bug

### ISSUE THREAD

**Issue by kimlisa** [gravitational/next#965] opened 2022-03-09 20:48 UTC
Links with hashes does not make our left navigation expand ie: https://goteleport.com/docs/setup/reference/cli/#tctl
(this was a result of using the search bar and clicking on a result)

Versus without hash correctly expands navigation ie: https://goteleport.com/docs/setup/reference/cli/

I get kinda lost when the side navigation does not expand, b/c normally I want to browse other subset of the stuff i searched

using chrome on linux

**Comment by C-STYR** [comment] 2022-03-17 22:31
@Alqanar can this issue be closed?

**Comment by Alqanar** [comment] 2022-03-18 15:53
@C-STYR  I'm not sure :) if it is enough that the issue is implemented in the gravitational/docs repository, then of course we can close it.

**Comment by C-STYR** [comment] 2022-03-18 16:36
@Alqanar please duplicate here then - not sure when we are going to cut docs over.  Thanks.

**Closed** 2022-03-22 11:47 UTC
